spring:
  application:
    name: ${SPRING_APPLICATION_NAME:workplace-tracker-service}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}

  main:
    allow-bean-definition-overriding: ${SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING:true}

  banner:
    location: ${SPRING_BANNER_LOCATION:classpath:banner.txt}
    mode: ${SPRING_BANNER_MODE:console}

  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
      roles: ${ADMIN_ROLES:ACTUATOR_ADMIN}

  # Jackson configuration for date/time handling
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: ${JACKSON_TIME_ZONE:UTC}

  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:db/changelog/db.changelog-master.xml}
    enabled: ${LIQUIBASE_ENABLED:true}

  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:workplace_tracker_db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    properties:
      charSet: ${DATASOURCE_CHARSET:UTF-8}
    hikari:
      minimum-idle: ${HIKARI_MINIMUM_IDLE:2}
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:25}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:10000}
      pool-name: ${HIKARI_POOL_NAME:HikariCP}
      max-lifetime: ${HIKARI_MAX_LIFETIME:7200000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      schema: ${HIKARI_SCHEMA:test}

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        default_schema: ${JPA_DEFAULT_SCHEMA:test}
        globally_quoted_identifiers: ${JPA_GLOBALLY_QUOTED_IDENTIFIERS:true}
        dialect: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${JPA_FORMAT_SQL:true}
        jdbc:
          time_zone: ${JPA_JDBC_TIME_ZONE:Asia/Kolkata}
          lob:
            non_contextual_creation: ${JPA_JDBC_LOB_NON_CONTEXTUAL_CREATION:true}

encryption:
  aes:
    algorithm: ${AES_ALGORITHM:AES}
    secret-key: ${AES_SECRET_KEY:Xf9aLp3qzT7vN2sYgW5KbVc6Rm8QJ0dP}

app:
  daily-view:
    max-range-days: ${DAILY_VIEW_MAX_RANGE:366}
  backup:
    directory: ${BACKUP_DIRECTORY:C:\Backup\Database\workplace_tracker_db}
    prefix: ${BACKUP_PREFIX:db_backup}
    default-db: ${BACKUP_DEFAULT_DB:workplace_tracker_db}

  jwt:
    secret: ${APP_JWT_SECRET:my-super-secret-key-which-is-at-least-32-characters-long!}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:3600000}
    allowed-clock-skew-sec: ${APP_JWT_ALLOWED_CLOCK_SKEW_SEC:10}

ui:
  host: ${UI_HOST:http://localhost,http://127.0.0.1,http://192.168.1.11}
  port: ${UI_PORT:3010}

server:
  port: ${SERVER_PORT:8010}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.sid: ${LOGGING_LEVEL_COM_SID:INFO}
    org.liquibase: ${LOGGING_LEVEL_LIQUIBASE:DEBUG}
    org.springframework.boot.autoconfigure.liquibase: ${LOGGING_LEVEL_SPRING_LIQUIBASE:DEBUG}
