spring:
  application:
    name: workplace-tracker-service

  main:
    #banner-mode: "off"  # Disable startup banner
    allow-bean-definition-overriding: true

  banner:
    location: classpath:banner.txt  # Custom banner file

  security:
    user:
      name: ${ADMIN_USERNAME:admin}      # Admin username (override via env variable)
      password: ${ADMIN_PASSWORD:admin}  # Admin password (override via env variable)
      roles: ACTUATOR_ADMIN

  # Liquibase Configuration (For Database Versioning)
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  # Database Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:workplace_tracker_db}
    username: ${DB_USERNAME:postgres}   # Securely fetch from env variable
    password: ${DB_PASSWORD:root}       # Securely fetch from env variable
    properties:
      charSet: UTF-8
    hikari:
      minimum-idle: 2
      maximum-pool-size: 25
      idle-timeout: 10000
      pool-name: HikariCP
      max-lifetime: 7200000
      connection-timeout: 30000
      schema: dev

  # JPA & Hibernate Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: dev
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
          lob:
            non_contextual_creation: true  # Prevents unnecessary warnings for BLOB fields

encryption:
  aes:
    algorithm: ${AES_ALGORITHM:AES}
    secret-key: ${AES_SECRET_KEY:Xf9aLp3qzT7vN2sYgW5KbVc6Rm8QJ0dP}

app:
  backup:
    directory: C:\Backup\Database\workplace_tracker_db  # Change this to your desired backup location
    prefix: db_backup
    default-db: workplace_tracker_db

  # JWT configuration - IMPORTANT: override these via environment variables in production
  jwt:
    # Provide a secure secret of at least 32 characters via env or secrets manager (do NOT commit a production secret here)
    secret: ${APP_JWT_SECRET:my-super-secret-key-which-is-at-least-32-characters-long!}
    # Token lifetime in milliseconds (default: 1 hour)
    expiration-ms: ${APP_JWT_EXPIRATION_MS:3600000}
    # Allowed clock skew in seconds to tolerate tiny clock differences (default: 10s)
    allowed-clock-skew-sec: ${APP_JWT_ALLOWED_CLOCK_SKEW_SEC:10}

ui:
  host: ${UI_HOST:http://localhost,http://127.0.0.1,http://192.168.1.11}
  port: ${UI_PORT:3010}

server:
  port: ${SERVER_PORT:8010}  # Server port, configurable via environment variable

# Logging Configuration
logging:
  level:
    root: INFO
    com.sid: INFO  # Debug mode enabled for specific package