spring:
  application:
    name: workplace-tracker-service

  main:
    allow-bean-definition-overriding: true

  banner:
    location: classpath:banner.txt

  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
      roles: ACTUATOR_ADMIN

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    # Prefer SPRING_DATASOURCE_URL if provided, otherwise build from DB_HOST/DB_PORT/DB_NAME
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:workplace_tracker_db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    properties:
      charSet: UTF-8
    hikari:
      minimum-idle: 2
      maximum-pool-size: 25
      idle-timeout: 10000
      pool-name: HikariCP
      max-lifetime: 7200000
      connection-timeout: 30000
      schema: dev

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: ${JPA_DEFAULT_SCHEMA:dev}
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
          lob:
            non_contextual_creation: true

encryption:
  aes:
    algorithm: ${AES_ALGORITHM:AES}
    secret-key: ${AES_SECRET_KEY:Xf9aLp3qzT7vN2sYgW5KbVc6Rm8QJ0dP}

app:
  backup:
    directory: C:\Backup\Database\workplace_tracker_db
    prefix: db_backup
    default-db: workplace_tracker_db

  jwt:
    secret: ${APP_JWT_SECRET:my-super-secret-key-which-is-at-least-32-characters-long!}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:3600000}
    allowed-clock-skew-sec: ${APP_JWT_ALLOWED_CLOCK_SKEW_SEC:10}

ui:
  host: ${UI_HOST:http://localhost,http://127.0.0.1,http://192.168.1.11}
  port: ${UI_PORT:3010}

server:
  port: ${SERVER_PORT:8010}

logging:
  level:
    root: INFO
    com.sid: INFO