# k8s/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workplace-tracker-deployment
  labels:
    app: workplace-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workplace-tracker
  template:
    metadata:
      labels:
        app: workplace-tracker
    spec:
      containers:
        - name: workplace-tracker
          image: siddhantpatni0407/workplace-tracker-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8010
              name: http
          envFrom:
            - configMapRef:
                name: workplace-tracker-config
            - secretRef:
                name: workplace-tracker-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
